version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/src
    ports:
      - "1313:1313"
    environment:
      HUGO_CACHEDIR: /tmp/hugo-cache
