name: Check Broken Links (markdown-link-check)

on:
  # Manual trigger only to test this alternative approach
  workflow_dispatch:

jobs:
  dead-links:
    name: Check for dead links
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install markdown-link-check
        run: sudo npm install -g markdown-link-check@3.8.7
      
      - name: Create config file
        run: |
          cat > .dlc.json << 'EOF'
          {
            "ignorePatterns": [
              { "pattern": "^https://example\\.com" },
              { "pattern": "^https://example\\.org" },
              { "pattern": "^https://localhost" },
              { "pattern": "^https://127\\.0\\.0\\.1" },
              { "pattern": "^https://0\\.0\\.0\\.0" },
              { "pattern": "^https://((www\\.)?linkedin\\.com)" },
              { "pattern": "^https://((www\\.)?twitter\\.com)" },
              { "pattern": "^https://((www\\.)?facebook\\.com)" },
              { "pattern": "\\.pdf$" },
              { "pattern": "^file://" }
            ],
            "timeout": "20s",
            "retryOn429": true,
            "retryCount": 3,
            "fallbackRetryDelay": "30s",
            "aliveStatusCodes": [200, 206, 301, 302, 303, 307, 308, 429]
          }
          EOF
      
      - name: Check markdown links
        run: |
          echo "Checking markdown files for dead links..."
          EXIT_CODE=0
          for file in $(find . -name "*.md" -not -path "./node_modules/*" -not -path "./.git/*"); do
            echo "Checking $file"
            if ! markdown-link-check -c .dlc.json -q "$file"; then
              EXIT_CODE=1
              echo "::error::Dead links found in $file"
            fi
          done
          exit $EXIT_CODE 