name: Check Broken Links

on:
  pull_request:
    types: [opened, synchronize, reopened]
  # Optional: Add scheduled checks
  # schedule:
  #   - cron: "0 0 * * 0"  # Runs once every Sunday

jobs:
  check-links:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Setup Node.js for theme dependencies
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # Install theme dependencies
      - name: Install dependencies
        run: |
          if [ -f "package.json" ]; then
            npm ci
          fi

      # Build the Hugo site first to handle rendering
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.110.0'  # Use a specific version known to work with your theme
          extended: true

      # Check for Hugo config
      - name: Check Hugo configuration
        run: |
          if [ -f "config.toml" ]; then
            echo "Using config.toml"
          elif [ -f "config.yaml" ]; then
            echo "Using config.yaml"
          elif [ -f "config.json" ]; then
            echo "Using config.json"
          else
            echo "No Hugo config found"
          fi
          
          # Print theme info
          if [ -d "themes" ]; then
            echo "Themes directory contents:"
            ls -la themes/
          fi

      # Simple external link check to avoid Hugo build issues
      - name: Check External Links Only
        id: lychee-external
        uses: lycheeverse/lychee-action@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          args: >-
            --cache
            --max-cache-age 48h
            --verbose
            --no-progress
            --exclude-path ".git"
            --exclude-path "node_modules"
            --exclude-path "themes"
            --scheme "https"
            --scheme "http"
            --max-retries 5
            --timeout 30
            --max-concurrency 8
            --retry-wait-time 3
            './**/*.md' 
            './**/*.html' 
            './**/*.txt'
          fail: true
          format: markdown
          output: ./lychee-external-report.md

      # If you want to post check results as PR comments, uncomment the following step
      # - name: Create Comment
      #   uses: peter-evans/create-or-update-comment@v3
      #   if: github.event_name == 'pull_request' && steps.lychee-external.outputs.exit_code != 0
      #   with:
      #     issue-number: ${{ github.event.pull_request.number }}
      #     body-file: ./lychee-external-report.md